### ISSUE TITLE
Error on rule generate_salmon_index 

### ISSUE THREAD

**Issue by galopyz** [tgbrooks/circadian_comparison#1]
Hi,

I am new to bioinformatics and learning about all the toolsets. I am trying to run your code on my local machine.

However, I ran into an issue with the rule generate_salmon_index in Snakefile. 

I do not have the following files, and the program raises errors:

-  /project/itmatlab/index/SALMON-1.4.0/Mus_musculu.GRCm38.75/Mus_musculus.GRCm38.75.TranscriptSeq.std.merged_with.dna.primary_assembly.fa
- /project/itmatlab/index/SALMON-1.4.0/Mus_musculu.GRCm38.75/index/decoy_names.txt. 

Is there any way I can get hold of these files or generate them?

Thank you.

**Comment by tgbrooks** [comment]
Apologies for the oversight. These weren't included due to their large size. They can be created with the following:

```
wget http://ftp.ensembl.org/pub/release-75/fasta/mus_musculus/dna/Mus_musculus.GRCm38.75.dna.primary_assembly.fa.gz
wget http://ftp.ensembl.org/pub/release-75/fasta/mus_musculus/cdna/Mus_musculus.GRCm38.75.cdna.all.fa.gz
wget http://ftp.ensembl.org/pub/release-75/fasta/mus_musculus/ncrna/Mus_musculus.GRCm38.75.ncrna.fa.gz

zcat  Mus_musculus.GRCm38.75.cdna.all.fa.gz Mus_musculus.GRCm38.75.ncrna.fa.gz Mus_musculus.GRCm38.75.dna.primary_assembly.fa.gz > Mus_musculus.GRCm38.75.TranscriptSeq.std.merged_with.dna.primary_assembly.fa

grep "^>" <(gunzip -c Mus_musculus.GRCm38.75.dna_rm.primary_assembly.fa.gz) | cut -d " " -f 1 > decoy_names.txt
sed -i.bak -e 's/>//g' decoy_names.txt
```

Note you might want to update the annotation version, which was ENSEMBL release 75 in our paper but that is pretty old at this point.

**Comment by galopyz** [comment]
Thank you very much!
